@CasinoApi_HostAddress = luckyapi-fje0bxcph0gyfmf3.germanywestcentral-01.azurewebsites.net

### Get all users
GET {{CasinoApi_HostAddress}}/api/users
Accept: application/json

### Get user by ID
GET {{CasinoApi_HostAddress}}/api/users/1
Accept: application/json

### Create a new user
POST {{CasinoApi_HostAddress}}/api/users
Content-Type: application/json



### Get all games
GET {{CasinoApi_HostAddress}}/api/games
Accept: application/json