swagger: "2.0"
openapi: 3.0.0
info:
  title: LuckyVegas API
  version: 1.0.0
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input

  /login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials

components:
  schemas:
    UserRegister:
      type: object
      required:
        - nickname
        - email
        - phone
        - password
        - passwordConfirmation
      properties:
        nickname:
          type: string
        email:
          type: string
        phone:
          type: string
        password:
          type: string
        passwordConfirmation:
          type: string
    UserLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
